notifications:
  email: false

language: cpp
sudo: false

# if pull request: always build
# if push: only build for master branch
if: (type != push) OR (type = push AND branch = lv2)

matrix:
  include:
    - name: "linux"
      os: linux
      dist: xenial
      sudo: required
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - freeglut3-dev
            - g++
            - libasound2-dev
            - libcurl4-openssl-dev
            - libfreetype6-dev
            - libjack-jackd2-dev
            - libx11-dev
            - libxcomposite-dev
            - libxcursor-dev
            - libxinerama-dev
            - libxrandr-dev
            - mesa-common-dev
            - ladspa-sdk
            - webkit2gtk-4.0
            - libgtk-3-dev
      services:
        - xvfb
      env:
        - BUILD_FOLDER="LinuxMakefile"
        - PROJUCER_EXPORT="$TRAVIS_BUILD_DIR/Plugin/Juce/extras/Projucer/Builds/LinuxMakefile/build/Projucer"

script:
  - cd $TRAVIS_BUILD_DIR/Plugin/
  - bash build_lv2.sh
  - echo "SUCCESS"
